### ISSUE TITLE
Consider More Mainstream License

### ISSUE THREAD

**Issue by cwfitzgerald** [GoldsteinE/name-it#13]
Cool crate, definitely useful as a stopgap until TAIT shows up!

One problem is the license is not a generally recognized one (it's not on https://opensource.org/licenses/alphabetical for example) which makes this crate not really usable for anyone who has real licensing concerns. Do consider something like the standard MIT OR Apache, or the fun combo of MIT OR Apache OR Zlib for maximum usability.

**Comment by GoldsteinE** [comment]
It's a permissive license, so it can be used everywhere MIT can be used. I'll consider adding “or Apache 2.0, at your option” though.

**Comment by cwfitzgerald** [comment]
The problem isn't the liberality, it's the widespread acceptance of the license. Lawyers generally get antsy about licenses without widespread approval, so adding the apache addition would solve this problem!
